name: Build and Test

on:
  push:
    branches: [ main, master]
  pull_request:
    branches: [ main, master]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        brew install libjpeg libpng libogg libvorbis
    - name: building and testing
      run: |
        ./cmakew -t .